name: CI
on: [push]

jobs:
  # Build an image and push to DockerHub so others don't need to build the environment on each run
  build_container:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Image & Push to DockerHub
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t hamelsmu/nbdev -f Dockerfile .
        docker push hamelsmu/nbdev
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # Make test run on the environment we built
  nbdev:
    name: Run nbdev checks
    needs: build_container
    runs-on: ubuntu-latest
    # use the container to run the checks
    container: hamelsmu/nbdev
    steps:
    - uses: actions/checkout@v1
    - name: Read all notebooks
      run: |
        nbdev_read_nbs
    - name: Check if all notebooks are cleaned
      run: |
        echo "Check we are starting with clean git checkout"
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        echo "Trying to strip out notebooks"
        nbdev_clean_nbs
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run tools/run-after-git-clone"; false; fi
    - name: Check if there is no diff library/notebooks
      run: |
        if [-n "$(nbdev_diff_nbs)"]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
    - name: Run tests
      run: |
        nbdev_test_nbs
